title: Ice's Homepage
page-top-title: Icedududu(Liu hanbing)
top-section-bg-text: How are you I am fine thanks and you
home-subtitle: Ice&ensp;|&ensp;刘寒冰
copyright-text: '&copy; Ice 2023-2026. All Rights Reserved.'
